### PR TITLE
fix: item published type

### LINKED ISSUE #292: FIX | itemPublishEntry
Edit ItemPublish type ti have a `totalViews` as a number

### PR DESCRIPTION
**Pull request by LinaYahya**
closes #292

### CODE REVIEW

File: src/constants/triggers.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+export enum Triggers {
+  COLLECTION_VIEW = 'collection-view',
+  ITEM_VIEW = 'item-view',
+  LINK_OPEN = 'link-open',
+  ITEM_DOWNLOAD = 'item-download',
```
Comment (spaenleh) [inline src/constants/triggers.ts:5]: We try to apply the PascalCase Naming convention for enums. 
```suggestion
  CollectionView = 'collection-view',
  ItemView = 'item-view',
  LinkOpen = 'link-open',
  ItemDownload = 'item-download',
```

**Review by spaenleh — CHANGES_REQUESTED** [review]
🏋️‍♀️ Just a naming convention comment, otherwise looks good !

**Review by spaenleh — APPROVED** [review]
🦒
