### PR TITLE
fix: use `DiscriminatedItem` instead of `Item`

### LINKED ISSUE #270: Fix `ActionData` typing
https://github.com/graasp/graasp-query-client/pull/430#discussion_r1334235919

### PR DESCRIPTION
**Pull request by spaenleh**
This PR updates the types to use `DiscriminatedItem` instead of `Item`.

This way the Record type of the key `item` will match `ItemRecord` since `ItemRecord` derives from `DiscriminatedItem` and not  `Item`.

close #270

### CODE REVIEW

File: src/services/members/interfaces/member.ts [hunk 1]
```diff
@@ -17,6 +17,12 @@ export interface Member {
   id: UUID;
   name: string;
   email: string;
+}
+
+export interface CompleteMember {
+  id: UUID;
+  name: string;
+  email: string;
```
Comment (pyphilia) [inline src/services/members/interfaces/member.ts:25]: Does it make sense to reuse `Member`? 
```
CompleteMember = Member & { ... }
```

Comment (spaenleh) [reply src/services/members/interfaces/member.ts:25]: @pyphilia You can not do that with interfaces. But I can change them to be type aliases instead.
