### PR TITLE
fix: deprecate host and protocol in `buildItemLinkForBuilder`

### LINKED ISSUE #54: Fix `buildBuilderItemLink` to support including protocol in `hostname`

### PR DESCRIPTION
**Pull request by spaenleh**
This PR deprecates the use of the `host` and `protocol` parameters in `buildItemLinkForBuilder`.
It introduces a new function signature with `origin` parameter which is either a string like `https://example.com` or an object with mandatory properties `{ hostName: string; protocol: string }`.

closes #54

### CODE REVIEW

File: test/fixtures.ts [hunk 1]
```diff
@@ -9,3 +9,4 @@ export const MOCK_ITEM_ID = '1234';
 export const MOCK_LANG = 'en';
 
 export const MOCK_HOST = 'myhost';
+export const MOCK_HOST_WITH_PROTO = 'http://myhost.com';
```
Comment (pyphilia) [inline test/fixtures.ts:12]:
```suggestion
export const MOCK_HOST_WITH_PROTOCOL = 'http://myhost.com';
```

File: src/config.ts [hunk 2]
```diff
@@ -1,3 +1,4 @@
 export const DEFAULT_LANG = 'en';
 export const DEFAULT_EXPORT_ACTIONS_VALIDITY_IN_DAYS = 7;
-export const DEFAULT_PROTOCOL = 'http';
+export const DEFAULT_PROTOCOL = 'https';
+export const PROTO_REGEX = /https?:\/\//;
```
Comment (pyphilia) [inline src/config.ts:4]:
```suggestion
export const PROTOCOL_REGEX = /https?:\/\//;
```
